services:
  server:
    image: node-typescript-express-docker-starter
    volumes:
      - 'files:/app/files'
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'

volumes:
  files:
